name: Build
on: [push, pull_request]
jobs:
  build-app:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14.8.0

      - name: Get deps
        run: yarn install --production

      - name: Add `node_modules/.bin` to PATH
        run: echo $(yarn bin) >> $GITHUB_PATH

      - name: "Check elm-format"
        uses: sparksp/elm-format-action@v1

      - name: "Check elm-review"
        uses: sparksp/elm-review-action@v1.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build asset
        run: yarn build

      - name: Publish Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.FRONT_END_WEBHOOK }}

